{% set name = "metatensor-core" %}
{% set version = "0.2.5" %}

package:
  name: python-{{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/metatensor_core-{{ version }}.tar.gz
  sha256: 1e24dc11620f108ce99009021f9245694dab755bced2e39bdd83452a03cd9a61

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    # Don't build metatensor-core, but use the already compiled `libmetatensor` package
    - METATENSOR_CORE_PYTHON_USE_EXTERNAL_LIB="ON"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    # Nothing will be built but we need correct env to make pip happy
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - python
    - setuptools >=77
    - packaging >=23
    - pip
    - libmetatensor {{ version }}
  run:
    - python
    - libmetatensor {{ version }}
    - numpy
    - ctypes-dlpack

test:
  imports:
    - metatensor
  commands:
    - pip check
  requires:
    - python
    - pip

about:
  home: https://github.com/metatensor/metatensor
  summary: Python bindings for metatensor-core
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: docs.metatensor.org


extra:
  recipe-maintainers:
    - HaoZeke
    - PicoCentauri
    - Luthaf
