{% set name = "metatensor-core" %}
{% set version = "0.1.12" %}

package:
  name: python-{{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/metatensor_core-{{ version }}.tar.gz
  sha256: b0b9c0386117e2ebfeff47e0a607e478cb24aa74337eaa69a528d16e6fd3a217

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    # Don't build metatensor-core, but use the already compiled `libmetatensor` package
    - METATENSOR_CORE_PYTHON_USE_EXTERNAL_LIB="ON"

requirements:
  build:
    # Nothing will be built but we need correct env to make pip happy
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - python {{ python_min }}
    - setuptools >=75
    - packaging >=23
    - pip
    - libmetatensor
  run:
    - python >={{ python_min }}
    - libmetatensor
    - numpy

test:
  imports:
    - metatensor
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/lab-cosmo/metatensor
  summary: Python bindings for metatensor-core
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: docs.metatensor.org


extra:
  recipe-maintainers:
    - PicoCentauri
    - Luthaf
